version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: api-esperanza-vida
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    container_name: dashboard-esperanza-vida
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - api